name: ${project.name}
main: com.github.siloneco.omikuji.Omikuji
version: ${project.version}
author: mikan010
description: ${project.description}
softdepend: [ "Vault" ]
api-version: 1.21
commands:
  omikuji:
    aliases: [ "omikuzi" ]
permissions:
  omikuji.allowdraw:
    default: true
  omikuji.command.omikuji:
    default: true
  omikuji.admin:
    default: op
  omikuji.bypass.drawtimelimit:
    default: op
  omikuji.bypass.cost:
    default: op
  omikuji.bypass.amount:
    default: op